server:
  port: 8082
  servlet:
    contextPath: /circuitbraker
spring:
  application:
    name: "circuitbraker-xbc"
  webflux:
    base-path: /circuitbraker
management.health.circuitbreakers.enabled: true

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 3
      minimumNumberOfCalls: 2
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      recordExceptions:
        - flexibility.client.connector.ProviderException
    shared:
      slidingWindowSize: 100
      permittedNumberOfCallsInHalfOpenState: 30
      waitDurationInOpenState: 1s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
  instances:
    flexPayment:
      baseConfig: default